[package]
name = "stand-alone-test"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
base = { path = "../base" }
hnsw = { path = "../hnsw" }
nhq = { path = "../nhq" }
rayon = { path = "../rayon" }
thiserror = "1.0.58"

[lints]
workspace = true
